### PR TITLE
Add wildcard for Cors

### PR DESCRIPTION
**Pull request by ebisbe**
I've followed this Docs https://fastapi.tiangolo.com/tutorial/cors/

### CODE REVIEW

**Comment by ebisbe** [comment]
@choss Your solution is not working for me...

**Comment by choss** [comment]
Do you have some demo code I can run on my local machine foe the website?

**Comment by ebisbe** [comment]
mmm not right now. I can set up something later. I think it's maybe related to the way I call the script `sudo python3 ebisbe_rest_api/rest.py nocors &>rest_output.log &` I  call it that way in order to get all the response and store it in a file so I can run the server like a background process. 
I removed this conditional https://github.com/choss/joycontrol_rest_api/blob/2a718ceec364107e9fa135fcc7ca54687e7abad7/rest.py#L108 and align as py would want but still did not work. So I ended copying what I had in this PR.

**Comment by choss** [comment]
I've changed how it's implemented and it works now:
create .env file with _ALLOW_ALL_CORS=True_ in the same folder.

**Pull request closed without merging**
